services:
  - type: web
    name: lingualink-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: STEAM_API_KEY
        sync: false
      - key: STEAM_API_SECRET
        sync: false
      - key: JWT_SECRET_KEY
        sync: false 